//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/leachCentralized/LeachCentralizedRoutingPacket.msg.
//

#ifndef _LEACHCENTRALIZEDROUTINGPACKET_M_H_
#define _LEACHCENTRALIZEDROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Struct generated from src/node/communication/routing/leachCentralized/LeachCentralizedRoutingPacket.msg:8 by nedtool.
 */
struct nodeData1
{
    nodeData1();
    int id;
    int serialNo;
    double energy;
};

void doPacking(cCommBuffer *b, nodeData1& a);
void doUnpacking(cCommBuffer *b, nodeData1& a);

/**
 * Enum generated from <tt>src/node/communication/routing/leachCentralized/LeachCentralizedRoutingPacket.msg:15</tt> by nedtool.
 * <pre>
 * enum LeachCentralizedRoutingPacket_Type
 * {
 * 
 *     LEACHCENTRALIZED_ROUTING_DATA_PACKET = 1;
 *     LEACHCENTRALIZED_FIND_NEIGHBOURS_PACKET = 2;
 * }
 * </pre>
 */
enum LeachCentralizedRoutingPacket_Type {
    LEACHCENTRALIZED_ROUTING_DATA_PACKET = 1,
    LEACHCENTRALIZED_FIND_NEIGHBOURS_PACKET = 2
};

/**
 * Class generated from <tt>src/node/communication/routing/leachCentralized/LeachCentralizedRoutingPacket.msg:21</tt> by nedtool.
 * <pre>
 * packet LeachCentralizedRoutingPacket extends RoutingPacket
 * {
 *     nodeData1 info;
 *     int numOfPackets;
 * 
 *     int LeachCentralizedRoutingPacketKind @enum(LeachCentralizedRoutingPacket_Type);
 *     int schedule[];
 * }
 * </pre>
 */
class LeachCentralizedRoutingPacket : public ::RoutingPacket
{
  protected:
    nodeData1 info_var;
    int numOfPackets_var;
    int LeachCentralizedRoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;

  private:
    void copy(const LeachCentralizedRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LeachCentralizedRoutingPacket&);

  public:
    LeachCentralizedRoutingPacket(const char *name=NULL, int kind=0);
    LeachCentralizedRoutingPacket(const LeachCentralizedRoutingPacket& other);
    virtual ~LeachCentralizedRoutingPacket();
    LeachCentralizedRoutingPacket& operator=(const LeachCentralizedRoutingPacket& other);
    virtual LeachCentralizedRoutingPacket *dup() const {return new LeachCentralizedRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual nodeData1& getInfo();
    virtual const nodeData1& getInfo() const {return const_cast<LeachCentralizedRoutingPacket*>(this)->getInfo();}
    virtual void setInfo(const nodeData1& info);
    virtual int getNumOfPackets() const;
    virtual void setNumOfPackets(int numOfPackets);
    virtual int getLeachCentralizedRoutingPacketKind() const;
    virtual void setLeachCentralizedRoutingPacketKind(int LeachCentralizedRoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
};

inline void doPacking(cCommBuffer *b, LeachCentralizedRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LeachCentralizedRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _LEACHCENTRALIZEDROUTINGPACKET_M_H_

