//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/ga_C/GARoutingPacket.msg.
//

#ifndef _GAROUTINGPACKET_M_H_
#define _GAROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Struct generated from src/node/communication/routing/ga_C/GARoutingPacket.msg:8 by nedtool.
 */
struct nodeData2
{
    nodeData2();
    int id;
    int serialNo;
    double energy;
};

void doPacking(cCommBuffer *b, nodeData2& a);
void doUnpacking(cCommBuffer *b, nodeData2& a);

/**
 * Enum generated from <tt>src/node/communication/routing/ga_C/GARoutingPacket.msg:15</tt> by nedtool.
 * <pre>
 * enum GARoutingPacket_Type
 * {
 * 
 *     GA_ROUTING_ADV_PACKET = 1;
 *     GA_ROUTING_JOIN_PACKET = 2;
 *     GA_ROUTING_TDMA_PACKET = 3;
 *     GA_ROUTING_DATA_PACKET = 4;
 *     GA_ROUTING_FIND_NEIGHBOURS_PACKET = 5;
 * }
 * </pre>
 */
enum GARoutingPacket_Type {
    GA_ROUTING_ADV_PACKET = 1,
    GA_ROUTING_JOIN_PACKET = 2,
    GA_ROUTING_TDMA_PACKET = 3,
    GA_ROUTING_DATA_PACKET = 4,
    GA_ROUTING_FIND_NEIGHBOURS_PACKET = 5
};

/**
 * Class generated from <tt>src/node/communication/routing/ga_C/GARoutingPacket.msg:24</tt> by nedtool.
 * <pre>
 * packet GARoutingPacket extends RoutingPacket
 * {
 *     nodeData2 info;
 *     int numOfPackets;
 *     int GARoutingPacketKind @enum(GARoutingPacket_Type);
 *     int schedule[];
 * }
 * </pre>
 */
class GARoutingPacket : public ::RoutingPacket
{
  protected:
    nodeData2 info_var;
    int numOfPackets_var;
    int GARoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;

  private:
    void copy(const GARoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GARoutingPacket&);

  public:
    GARoutingPacket(const char *name=NULL, int kind=0);
    GARoutingPacket(const GARoutingPacket& other);
    virtual ~GARoutingPacket();
    GARoutingPacket& operator=(const GARoutingPacket& other);
    virtual GARoutingPacket *dup() const {return new GARoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual nodeData2& getInfo();
    virtual const nodeData2& getInfo() const {return const_cast<GARoutingPacket*>(this)->getInfo();}
    virtual void setInfo(const nodeData2& info);
    virtual int getNumOfPackets() const;
    virtual void setNumOfPackets(int numOfPackets);
    virtual int getGARoutingPacketKind() const;
    virtual void setGARoutingPacketKind(int GARoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
};

inline void doPacking(cCommBuffer *b, GARoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GARoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GAROUTINGPACKET_M_H_

