//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/MOED_CC/MOED_CC.msg.
//

#ifndef _MOED_CC_M_H_
#define _MOED_CC_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Struct generated from src/node/communication/routing/MOED_CC/MOED_CC.msg:8 by nedtool.
 */
struct nodeData
{
    nodeData();
    int id;
    int serialNo;
    double energy;
};

void doPacking(cCommBuffer *b, nodeData& a);
void doUnpacking(cCommBuffer *b, nodeData& a);

/**
 * Enum generated from <tt>src/node/communication/routing/MOED_CC/MOED_CC.msg:16</tt> by nedtool.
 * <pre>
 * enum MOED_CC_Packet_Type
 * {
 * 
 *     MOED_CC_ADV_PACKET = 1;
 *     MOED_CC_JOIN_PACKET = 2;
 *     MOED_CC_TDMA_PACKET = 3;
 *     MOED_CC_DATA_PACKET = 4;
 *     MOED_CC_FIND_NEIGHBOURS_PACKET = 5;
 * }
 * </pre>
 */
enum MOED_CC_Packet_Type {
    MOED_CC_ADV_PACKET = 1,
    MOED_CC_JOIN_PACKET = 2,
    MOED_CC_TDMA_PACKET = 3,
    MOED_CC_DATA_PACKET = 4,
    MOED_CC_FIND_NEIGHBOURS_PACKET = 5
};

/**
 * Class generated from <tt>src/node/communication/routing/MOED_CC/MOED_CC.msg:25</tt> by nedtool.
 * <pre>
 * packet MOED_CC_Packet extends RoutingPacket
 * {
 *     nodeData info;
 *     int numOfPackets;
 *     int MOED_CC_PacketKind @enum(MOED_CC_Packet_Type);
 *     int schedule[];
 * }
 * </pre>
 */
class MOED_CC_Packet : public ::RoutingPacket
{
  protected:
    nodeData info_var;
    int numOfPackets_var;
    int MOED_CC_PacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;

  private:
    void copy(const MOED_CC_Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MOED_CC_Packet&);

  public:
    MOED_CC_Packet(const char *name=NULL, int kind=0);
    MOED_CC_Packet(const MOED_CC_Packet& other);
    virtual ~MOED_CC_Packet();
    MOED_CC_Packet& operator=(const MOED_CC_Packet& other);
    virtual MOED_CC_Packet *dup() const {return new MOED_CC_Packet(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual nodeData& getInfo();
    virtual const nodeData& getInfo() const {return const_cast<MOED_CC_Packet*>(this)->getInfo();}
    virtual void setInfo(const nodeData& info);
    virtual int getNumOfPackets() const;
    virtual void setNumOfPackets(int numOfPackets);
    virtual int getMOED_CC_PacketKind() const;
    virtual void setMOED_CC_PacketKind(int MOED_CC_PacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
};

inline void doPacking(cCommBuffer *b, MOED_CC_Packet& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MOED_CC_Packet& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MOED_CC_M_H_

