//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/pso_C/PSORoutingPacket.msg.
//

#ifndef _PSOROUTINGPACKET_M_H_
#define _PSOROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Struct generated from src/node/communication/routing/pso_C/PSORoutingPacket.msg:8 by nedtool.
 */
struct nodeData
{
    nodeData();
    int id;
    int serialNo;
    double energy;
};

void doPacking(cCommBuffer *b, nodeData& a);
void doUnpacking(cCommBuffer *b, nodeData& a);

/**
 * Enum generated from <tt>src/node/communication/routing/pso_C/PSORoutingPacket.msg:15</tt> by nedtool.
 * <pre>
 * enum PSORoutingPacket_Type
 * {
 * 
 *     PSO_ROUTING_ADV_PACKET = 1;
 *     PSO_ROUTING_JOIN_PACKET = 2;
 *     PSO_ROUTING_TDMA_PACKET = 3;
 *     PSO_ROUTING_DATA_PACKET = 4;
 *     PSO_ROUTING_FIND_NEIGHBOURS_PACKET = 5;
 * }
 * </pre>
 */
enum PSORoutingPacket_Type {
    PSO_ROUTING_ADV_PACKET = 1,
    PSO_ROUTING_JOIN_PACKET = 2,
    PSO_ROUTING_TDMA_PACKET = 3,
    PSO_ROUTING_DATA_PACKET = 4,
    PSO_ROUTING_FIND_NEIGHBOURS_PACKET = 5
};

/**
 * Class generated from <tt>src/node/communication/routing/pso_C/PSORoutingPacket.msg:24</tt> by nedtool.
 * <pre>
 * packet PSORoutingPacket extends RoutingPacket
 * {
 *     nodeData info;
 *     int numOfPackets;
 *     int PSORoutingPacketKind @enum(PSORoutingPacket_Type);
 *     int schedule[];
 * }
 * </pre>
 */
class PSORoutingPacket : public ::RoutingPacket
{
  protected:
    nodeData info_var;
    int numOfPackets_var;
    int PSORoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;

  private:
    void copy(const PSORoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PSORoutingPacket&);

  public:
    PSORoutingPacket(const char *name=NULL, int kind=0);
    PSORoutingPacket(const PSORoutingPacket& other);
    virtual ~PSORoutingPacket();
    PSORoutingPacket& operator=(const PSORoutingPacket& other);
    virtual PSORoutingPacket *dup() const {return new PSORoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual nodeData& getInfo();
    virtual const nodeData& getInfo() const {return const_cast<PSORoutingPacket*>(this)->getInfo();}
    virtual void setInfo(const nodeData& info);
    virtual int getNumOfPackets() const;
    virtual void setNumOfPackets(int numOfPackets);
    virtual int getPSORoutingPacketKind() const;
    virtual void setPSORoutingPacketKind(int PSORoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
};

inline void doPacking(cCommBuffer *b, PSORoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PSORoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PSOROUTINGPACKET_M_H_

